version: "3.7"


services:
  web:
    build: 
      context: ./akundotdev
      dockerfile: Dockerfile.prod
    command: gunicorn akundev_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./akundotdev/:/usr/src/akundotdev/
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web