version: "3"

services:
    db:
        image: postgres:13-alpine
        volumes:
          - ./postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=hello_django
          - POSTGRES_PASSWORD=hello_django
          - POSTGRES_DB=hello_django_dev

    web:
        build: ./
        command: gunicorn -b 0.0.0.0:8000 -w 4 --worker-tmp-dir /dev/shm akundotdev_conf.wsgi:application
        #command: python3 manage.py runserver 0.0.0.0:8000 
        ports: 
          - 8000
        volumes: 
          - ./:/usr/src/code/
        depends_on:
          - db

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
          - web
