version: "3.7"


services:
  web:
    build: 
      context: ./akundotdev
      dockerfile: Dockerfile.prod
    command: gunicorn akundev_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/akundotdev/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/akundotdev/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  static_volume: