version: "3.7"


services:
  web:
    build: 
      context: ./akundotdev
      dockerfile: Dockerfile.prod
    command: gunicorn akundev_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/akundotdev/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/akundotdev/web/staticfiles
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


volumes:
  static_volume: