version: "3.7"


services:
  web:
    build: ./akundotdev
    command: gunicorn akundev_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./akundotdev/:/usr/src/akundotdev/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
